### PR TITLE
Ensure determinstic dict ordering to ensure builds are reproducible.

### PR DESCRIPTION
**Pull request by lamby**
See https://reproducible-builds.org/

Signed-off-by: Chris Lamb chris@chris-lamb.co.uk

### CODE REVIEW

**Comment by bitprophet** [comment]
Seems legit. Thanks!

**Comment by lamby** [comment]
Friendly ping on this? :)

**Comment by bitprophet** [comment]
Haven't gotten to clearing out my bugfix milestones yet - hope to soon! Sorry for the wait.

**Comment by lamby** [comment]
Any luck yet @bitprophet ? :)

**Comment by lamby** [comment]
Friendly ping on this @bitprophet ?  \*grin\*

**Comment by bitprophet** [comment]
Pings don't really help, sorry :D it gets done when it gets done! (Also, the last week has been...bad.)

**Comment by lamby** [comment]
> Pings don't really help, sorry :D it gets done when it gets done! (Also, the last week has been...bad.)

Sooo tempting to ping this PR ;-)

**Comment by bitprophet** [comment]
I haven't given Alabaster love in a while :sob: Hoping to do that once I get over a hump with my other projects. Not promising an ETA because every time I do I jinx myself 😩

**Comment by lamby** [comment]
♥

**Comment by lamby** [comment]
Gentle ping on this? Open since 2016 now :)

**Comment by AA-Turner** [comment]
Dictionaries are now ordered, so I think this PR isn't needed (thank you, though!)

A

**Pull request closed without merging**
