### PR TITLE
Rename alabaster.css_t to alabaster.css.jinja

### LINKED ISSUE #203: ``OldJinjaSuffixWarning`` for ``alabaster.css_t`` in unreleased Sphinx 6.2
I see the following warning, that our CI treats as error:

Do you foresee any issues with renaming the file?

```
 Warning, treated as error:
Failed to copy a file in html_static_file: /home/runner/work/sphinx-automodapi/sphinx-automodapi/.tox/py310-test-sphinxdev/lib/python3.10/site-packages/alabaster/static/alabaster.css_t: OldJinjaSuffixWarning("'/home/runner/work/sphinx-automodapi/sphinx-automodapi/.tox/py310-test-sphinxdev/lib/python3.10/site-packages/alabaster/static/alabaster.css_t': the '_t' suffix for Jinja templates is deprecated. If the file is a template, use the suffix '.jinja' instead. For more information, see https://www.sphinx-doc.org/en/master/development/theming.html#static-templates")
```

https://github.com/astropy/sphinx-automodapi/actions/runs/4694556705/jobs/8322825594#step:8:170

x-ref: https://github.com/astropy/sphinx-automodapi/issues/164

### PR DESCRIPTION
**Pull request by pllim**
To fix #203

### CODE REVIEW

**Review by jayaddison — CHANGES_REQUESTED** [review]
Hi @pllim - could you update the filename to `alabaster.css.jinja`?

(Sphinx copies theme-related files like this one as part of a Python [`copy_asset` method](https://github.com/sphinx-doc/sphinx/blob/5d13215b58f93c6be8255ef2e3e20836508c7d47/sphinx/util/fileutil.py#L65), and it will remove the suffix - either `_t` or `.jinja` - from any files considered templates that end with those. in this case, we'd like the destination file to be [`alabaster.css`, according to the alabaster `theme.conf`](https://github.com/sphinx-doc/alabaster/blob/f0cb3194610b8a6d17571d49b6aa8ca8b1edde8a/alabaster/theme.conf#L3), so either `alabaster.css_t` or `alabaster.css.jinja` should work)

**Comment by pllim** [comment]
Sure thing, I have renamed it. I apologize for misinterpreting the warning message.

If you want me to squash, let me know. Otherwise, I would recommend to use the "squash and merge" button here. Thanks!

**Comment by jayaddison** [comment]
Thanks @pllim - looking further into the build warnings you saw has made me wonder whether this particular change (recommending the `.jinja` suffix instead of `_t`) is ready-for-release in 6.2.0 - I wrote the change, and the Sphinx team has been supportive.. but I'm feeling a bit uncertain.

I mention that mainly because this change should only be applied if Sphinx 6.2.0 does decide to include support for `.jinja` (otherwise, we risk breaking the `alabaster` theme).

I've written some more thoughts here: https://github.com/sphinx-doc/sphinx/pull/11165#issuecomment-1509862003 - please let me know if I can explain more.

**Comment by pllim** [comment]
For now, we have ignored this warning in our test suite downstream, so there is no rush on my end. However, I will be interested to see how Sphinx would resolve this dilemma. Thanks for the link!

**Comment by jayaddison** [comment]
Thank you @pllim (and thank you also @bsipocz for reporting the problem).

I _think_ that my preference is to rollback the change and then re-consider it for inclusion in a later release.  That might be a very-cautious approach, but I'm volunteering on this so I'd also like to avoid causing too much frustration (both to myself and others).

I'll spend some more time thinking about the options and waiting for any further commentary in the Sphinx project.

**Comment by AA-Turner** [comment]
This would break support for all released versions of Sphinx! I'll close for now, discussion continues on https://github.com/sphinx-doc/sphinx/pull/11329.

A

**Pull request closed without merging**
